// <auto-generated />
namespace _31181020918_LeGiaPhuc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Movie : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Movie));
        
        string IMigrationMetadata.Id
        {
            get { return "202104071246352_Movie"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
